name: Upload release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build DLL
        run: make

      - name: Create ZIP file
        run: |
          powershell Compress-Archive -Path LICENSE, OBSReplayFolders.lua, detect_game.dll -DestinationPath obs-replay-folders.zip

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: obs-replay-folders.zip
